### ISSUE TITLE
建议部署成微信小程序插件，这样避免无法使用npm安装的尴尬

### ISSUE THREAD

**Issue by cleocn** [ianzhi/wxParse#1]
拷贝文件的方式比较麻烦。

采用微信小程序插件的方式，可以快速的更新版本。
避免无法使用npm安装的尴尬

**Comment by cleocn** [comment]
还有一个非常重要的就是mpvue等之类的第三方框架的使用者可以使用。

**Comment by ianzhi** [comment]
主要问题在于不能使用个人号开发插件，离职以后怎么继续维护是个问题。微信支持个人开发插件的可能性不大，目前只好用拷贝和npm安装的方式。

**Comment by cleocn** [comment]
离职只是原来的版本没有升级而已，用户使用是针对版本使用的。
新公司可以挂到新的插件上就是了。用户使用切换成本也还好。

**Comment by cleocn** [comment]
我找了几个版本这个表格都不正常，不知道你这个版本看看效果
https://freefundcdn.51xhd.cn/zbjst/17/2019-03-21/ae6ba0bc-4bb6-11e9-a755-52540034628f.html

**Comment by cleocn** [comment]
也是乱的：
![image](https://user-images.githubusercontent.com/778219/54814635-196a9c00-4ccb-11e9-82ab-ef478cf20d64.png)

**Comment by cleocn** [comment]
好的渲染要这样：
![image](https://user-images.githubusercontent.com/778219/54814723-45861d00-4ccb-11e9-8981-bfea424eb70a.png)

**Comment by ianzhi** [comment]
嗯，基本没有修改与表格有关的内容。已经加入修改计划，之后会更新~
另外，插件大概会在明天发布~

**Comment by cleocn** [comment]
太好了。

**Comment by cleocn** [comment]
非常感谢，进展怎样

**Comment by ianzhi** [comment]
插件已经提交审核，等待中~
表格的问题，更新后会修改更新列表~

**Comment by cleocn** [comment]
表格的问题好像有点难度哦，我看目前的版本都没有解决
是rowspan、colspan没有解析的问题。

**Comment by ianzhi** [comment]
嗯，是比较麻烦，不过可以把td补全，然后调节一下样式，‘看起来’是合并单元格。
完美解决，其实也不是不可能，就是放在小程序里面，计算压力感觉有点大，实现也挺麻烦，放在后端，感觉还行，生成一次可以缓存，我好好想一想吧，修复时间不定，烂尾也说不定~~^_^

**Comment by cleocn** [comment]
审核通过了没？
又有一个新的问题？
相对地址的问题， 能否能传个参数进去，能够作为图片的相对base url？

**Comment by ianzhi** [comment]
通过好久了，可以看一下说明文件~~
相对地址的问题，已经更新了~
