### ISSUE TITLE
能否在view上添加id属性功能

### ISSUE THREAD

**Issue by zzpmaster** [ianzhi/wxParse#11]
`html<div id='xx'> 转换为<view id='xxx'>`

**Comment by ianzhi** [comment]
现在不能吗，我试试，回头回复哈~

**Comment by zzpmaster** [comment]
> 现在不能吗，我试试，回头回复哈~

老版本wxParse是没有的。

**Comment by ianzhi** [comment]
已经改了，最晚明天更新吧~

**Comment by zzpmaster** [comment]
> 已经改了，最晚明天更新吧~

非常感谢~
