### ISSUE TITLE
不支持表情吗？

### ISSUE THREAD

**Issue by ialmost** [ianzhi/wxParse#12]
不支持表情吗？

**Comment by ianzhi** [comment]
/**
* WxParse.emojisInit(reg,baseSrc,emojis)
* 1.reg，如格式为[00]=>赋值 reg='[]'
* 2.baseSrc,为存储emojis的图片文件夹
* 3.emojis,定义表情键值对
*/
WxParse.emojisInit('[]', "/wxParse/emojis/", {
      "00": "00.gif",
      "01": "01.gif",
      "02": "02.gif",
      "03": "03.gif",
      "04": "04.gif",
      "05": "05.gif",
      "06": "06.gif",
      "07": "07.gif",
      "08": "08.gif",
      "09": "09.gif",
      "09": "09.gif",
      "10": "10.gif",
      "11": "11.gif",
      "12": "12.gif",
      "13": "13.gif",
      "14": "14.gif",
      "15": "15.gif",
      "16": "16.gif",
      "17": "17.gif",
      "18": "18.gif",
      "19": "19.gif",
    });
这样试试吧~

**Comment by ialmost** [comment]
我是用插件的方式




------------------ 原始邮件 ------------------
发件人: ian <notifications@github.com>
发送时间: 2019年5月16日 09:33
收件人: ianzhi/wxParse <wxParse@noreply.github.com>
抄送: Breeze <ialmost@qq.com>, Author <author@noreply.github.com>
主题: 回复：[ianzhi/wxParse] 不支持表情吗？ (#12)




/**
  
WxParse.emojisInit(reg,baseSrc,emojis) 

1.reg，如格式为[00]=>赋值 reg='[]' 

2.baseSrc,为存储emojis的图片文件夹 

3.emojis,定义表情键值对
 */
 WxParse.emojisInit('[]', "/wxParse/emojis/", {
 "00": "00.gif",
 "01": "01.gif",
 "02": "02.gif",
 "03": "03.gif",
 "04": "04.gif",
 "05": "05.gif",
 "06": "06.gif",
 "07": "07.gif",
 "08": "08.gif",
 "09": "09.gif",
 "09": "09.gif",
 "10": "10.gif",
 "11": "11.gif",
 "12": "12.gif",
 "13": "13.gif",
 "14": "14.gif",
 "15": "15.gif",
 "16": "16.gif",
 "17": "17.gif",
 "18": "18.gif",
 "19": "19.gif",
 });
 这样试试吧~

**Comment by ianzhi** [comment]
了解了，我看一下能不能实现~能的话尽快更新，不能就只能下载代码了~~

**Comment by ialmost** [comment]
感谢，只是因为急着用，又因为用的框架，只能用插件的方式，如果可以，能否帮忙先支持下




------------------ 原始邮件 ------------------
发件人: ian <notifications@github.com>
发送时间: 2019年5月16日 09:36
收件人: ianzhi/wxParse <wxParse@noreply.github.com>
抄送: Breeze <ialmost@qq.com>, Author <author@noreply.github.com>
主题: 回复：[ianzhi/wxParse] 不支持表情吗？ (#12)




了解了，我看一下能不能实现~能的话尽快更新，不能就只能下载代码了~~

**Comment by ianzhi** [comment]
好的~

**Comment by ialmost** [comment]
感谢🙏




------------------ 原始邮件 ------------------
发件人: ian <notifications@github.com>
发送时间: 2019年5月16日 09:42
收件人: ianzhi/wxParse <wxParse@noreply.github.com>
抄送: Breeze <ialmost@qq.com>, Author <author@noreply.github.com>
主题: 回复：[ianzhi/wxParse] 不支持表情吗？ (#12)




好的~

**Comment by ianzhi** [comment]
已修复，今天更新插件~~

**Comment by ianzhi** [comment]
不好意思哈，插件提交两次了都审核失败，通过我会尽快发布~

**Comment by ialmost** [comment]
> 不好意思哈，插件提交两次了都审核失败，通过我会尽快发布~

审核失败应该有提示原因吧？感谢给予这个问题的关注，谢谢！

**Comment by ianzhi** [comment]
有的，因为我写的插件说明不够详细，已经改了，试试吧，也不太清楚他们需要怎么样的说明

**Comment by ialmost** [comment]
> 有的，因为我写的插件说明不够详细，已经改了，试试吧，也不太清楚他们需要怎么样的说明

好的
