### ISSUE TITLE
wxss中存在不符合规则的选择器

### ISSUE THREAD

**Issue by ialmost** [ianzhi/wxParse#13]
VM15008:1 Some selectors are not allowed in component wxss, including tag name selectors, ID selectors, and attribute selectors.(./components/wxparse/wxparse.wxss:90:14)

![image](https://user-images.githubusercontent.com/6847189/58299488-db484080-7e11-11e9-96dd-731b4e6342f4.png)

text  image 是不能被当作选择器的

**Comment by ianzhi** [comment]
不好意思，我该怎么复现这个错误呢~

**Comment by ialmost** [comment]
> 不好意思，我该怎么复现这个错误呢~

在小程序引入并使用这个插件即可，给定的 html ，你可以使用这个试试
`<p>&nbsp;</p><p><img src="https://img.haomianjie.com/group1/M00/00/54/rBOiz1yR-uSASsAMAAATWaZYvFU475.png" style=""/></p><p><img src="https://img.haomianjie.com/group1/M00/00/54/rBOiz1yR-ueAXc66AAIXkdZSQ0s254.jpg" style=""/></p><p><img src="https://img.haomianjie.com/group1/M00/00/54/rBOiz1yR-umAAHBnAAHmdDvV8B4046.jpg" style=""/></p><p><br/></p>`

**Comment by ialmost** [comment]
另外，在插件的 /components/wxparse/wxparse.wxss 文件中，确实有使用的 text 和 image 作为选择器，可以先尝试改掉这2个，应该就没有问题了

**Comment by ianzhi** [comment]
修改了，已经提交审核~

**Comment by superlbr** [comment]
还有image
https://github.com/ianzhi/wxParse/blob/f258bdc3ddf7635ae2d4d78982ff96d90105f559/src/wxparse.wxss#L76-L80
