### ISSUE TITLE
图片宽度比屏小

### ISSUE THREAD

**Issue by sunzy** [ianzhi/wxParse#18]
![image](https://user-images.githubusercontent.com/1256354/60506532-9a88f480-9cf8-11e9-9fd9-0ae1620d8895.png)
article里的node里计算出来的宽度是375

![image](https://user-images.githubusercontent.com/1256354/60506599-bdb3a400-9cf8-11e9-8be9-e768423d0d9d.png)
而这里却有一个image的样式，高度是320

**Comment by ianzhi** [comment]
改了，下午传~~
