### ISSUE TITLE
“下载代码方式”使用wxprase报错！

### ISSUE THREAD

**Issue by RoseauHan** [ianzhi/wxParse#21]
**Describe the bug**
最近由于一些原因，需要改插件方式为下载代码方式来使用wxprase，于是我查看了[官方文档](https://www.dnote.cn/users/ianzhi/posts/xiazaidaimafangshi-kuaisukaishi-wxParsewendang)但是今天在尝试改变之后，一直在报错，无法使用，不知道是什么原因。我另外尝试过将src放到不同的位置，但是一直无法解决该问题。

基础库：2.3.2

**Screenshots**
目录结构及json文件如图：
![bug](https://user-images.githubusercontent.com/31185165/61069375-c154d280-a43e-11e9-8e81-d43edeaa7e9d.png)

请问是我的配置有问题吗？谢谢

**Comment by RoseauHan** [comment]
@ianzhi 谢谢！

**Comment by ianzhi** [comment]
wxparse目录下的js/wxml/wxss/json文件名都必须是小写，不好意思，没注意到~

**Comment by RoseauHan** [comment]
您好！我使用了您最新的代码，结果依然有错误！
![bug](https://user-images.githubusercontent.com/31185165/61171335-bcac2d80-a5a8-11e9-917b-8502eb8f1733.png)
