### ISSUE TITLE
能否提供给图片添加后缀的功能

### ISSUE THREAD

**Issue by ialmost** [ianzhi/wxParse#22]
详情展示的图，一般都会用到CDN压缩，所以可能有如下需求
www.ianzhi.com/image/ianzhi.jpg/someting_params
www.ianzhi.com/image/ianzhi.jpg?someting_params

**Comment by ialmost** [comment]
需求稍微复杂，后缀的参数还会涉及到图片的宽高，实现起来可能会比较复杂，先关闭了

**Comment by ialmost** [comment]
希望支持

**Comment by ianzhi** [comment]
收到，明天看一下哈~

**Comment by ianzhi** [comment]
插件请等待v1.0.11版本发布~
源代码已经提交，一样是v1.0.11版本~
