### ISSUE TITLE
添加自定义处理a标签事件

### ISSUE THREAD

**Issue by mateor95** [ianzhi/wxParse#23]
我的需求是当渲染的网页中a标签被点击时候，进行处理，因此我改成了：

    /**
     * 处理链接点击事件
     */
    wxParseTagATap: function (e) {
      // wx.setClipboardData({ data: e.currentTarget.dataset.src });
      this.triggerEvent('linkClick', e.currentTarget.dataset)
    }

**Comment by mateor95** [comment]
在组件中新增了linkClick事件，使用bind:linkClick进行绑定

**Comment by ianzhi** [comment]
收到~
