### ISSUE TITLE
图片 src 如果有参数，会多一对双引号，导致图片无法加载

### ISSUE THREAD

**Issue by xPixv** [ianzhi/wxParse#7]
**Describe the bug**
原图片 `src="https://steamcdn-a.akamaihd.net/steam/apps/842810/ss_48fc332194f446f025dc8ab3af9dc1ed960ec947.1920x1080.jpg?t=1536588237"`

图中图片 src 最后包含参数 `?t=1536588237`，渲染 wxml 后 `image` 的 `src` 和 `data-src` 均多一对双引号
![image](https://user-images.githubusercontent.com/9652227/55453931-74c45480-5610-11e9-8750-b697511ad149.png)

然后就 404 了
![image](https://user-images.githubusercontent.com/9652227/55454062-059b3000-5611-11e9-8279-10f0de2bb410.png)

没有参数的图片是正常的

（PS：原作者的 wxParse 没有这个问题

**Comment by xPixv** [comment]
最新的 commit 对 attr regexp 的修改引入的这个问题，上一个版本的 regexp 就没问题

https://github.com/ianzhi/wxParse/blob/e535a92534b5fe11bde02edbc5508363e7ca98b0/src/wxparse/config.js#L12

**Comment by ianzhi** [comment]
ok，考虑欠妥了，我改回去吧
