### ISSUE TITLE
word标签的支持

### ISSUE THREAD

**Issue by Easyzhan** [ianzhi/wxParse#9]
![image](https://user-images.githubusercontent.com/8928783/56545420-20c2e500-65aa-11e9-8c9c-c9eeed251aac.png)

![image](https://user-images.githubusercontent.com/8928783/56545439-2ae4e380-65aa-11e9-98a3-e36464797c23.png)

从word复制来的解析不了唉

**Comment by ianzhi** [comment]
你可以粘贴一下具体的代码~尽量解决~

**Comment by ianzhi** [comment]
这个可能没法解决了。
word文档的解析就太麻烦了，建议在服务器端解析成html后再在小程序渲染。
